// Teste das Requisições REST dos prestadores
@baseURL = http://localhost:4000/api/prestadores

// GET - Lista todos os registros
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjUzNjdhNDAzNjJlNDg4M2NjOGUyOWMwIn0sImlhdCI6MTY5ODA2OTA1OSwiZXhwIjoxNjk4MzI4MjU5fQ.cLtXR2sCCdocxUISVG7WyX7_Sh8uYCZjKghlVg3YMi8


###
// GET - Lista um registro pelo id
GET {{baseURL}}/id/6563aafebc8f1824de8d0999
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjUzNjdhNDAzNjJlNDg4M2NjOGUyOWMwIn0sImlhdCI6MTY5ODA2OTA1OSwiZXhwIjoxNjk4MzI4MjU5fQ.cLtXR2sCCdocxUISVG7WyX7_Sh8uYCZjKghlVg3YMi8


###
// GET - Lista um registro pela razão social
GET {{baseURL}}/title/Niram (1999)
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjUzNjdhNDAzNjJlNDg4M2NjOGUyOWMwIn0sImlhdCI6MTY5ODA2OTA1OSwiZXhwIjoxNjk4MzI4MjU5fQ.cLtXR2sCCdocxUISVG7WyX7_Sh8uYCZjKghlVg3YMi8


###
// DELETE - Apaga um registro pelo id
DELETE {{baseURL}}/64ff261e0d4ff54ddb4d66c8
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjUzNjdhNDAzNjJlNDg4M2NjOGUyOWMwIn0sImlhdCI6MTY5ODA2OTA1OSwiZXhwIjoxNjk4MzI4MjU5fQ.cLtXR2sCCdocxUISVG7WyX7_Sh8uYCZjKghlVg3YMi8


###
// POST - Insere um novo registro
POST {{baseURL}}
Content-Type: application/json

{
    "actors" :"Kunchacko Boban, Shalini",
    "aka" : "Niram (1999)",
    "imdb_id" : "tt0255426",
    "rank" : 130452,
    "title" : "Niram",
    "year" : 1999,
    "director" : "Jose Sebastian"
}

###
// PUT - Altera o registro
PUT {{baseURL}}
Content-Type: application/json

{
    "actors": "Kamal Haasan, Sridevi",
    "aka": "Varumayin Niram Sigappu (1980)",
    "imdb_id": "tt0155329",
    "rank": 136991,
    "title": "Varumayin Niram Sigappu",
    "year": 1980,
    "director": "K. Balachander"
}

